// React Email Templates — Source code generators for transactional email components.
// Zero dependencies. Each function returns a complete React Email component file as a string.
// Users copy the output into their project alongside their own `react-email` installation.
// Returns null on errors and logs with console.error("[react-email-templates] ...").

const PKG = "[react-email-templates]";

// ─── Welcome Email ─────────────────────────────────────────────────────────────

/**
 * Generate a welcome email React Email component as a file string.
 *
 * The returned string is a complete `.tsx` file. Write it to
 * `emails/welcome.tsx` in your project and render via `react-email` CLI
 * or the Resend / Nodemailer integration.
 *
 * @param {object} [options]
 * @param {string} [options.appName="MyApp"]           - Your application name
 * @param {string} [options.appUrl="https://example.com"] - Your application URL
 * @param {string} [options.supportEmail="support@example.com"] - Support address shown in footer
 * @param {string} [options.primaryColor="#6366f1"]    - Brand accent color (hex)
 * @param {string} [options.logoUrl=""]                - Optional logo image URL
 * @returns {string|null} Complete TSX source string, or null on invalid input
 */
export function generateWelcomeEmail(options = {}) {
  try {
    const {
      appName = "MyApp",
      appUrl = "https://example.com",
      supportEmail = "support@example.com",
      primaryColor = "#6366f1",
      logoUrl = "",
    } = options;

    if (typeof appName !== "string" || !appName.trim()) {
      console.error(`${PKG} generateWelcomeEmail: appName must be a non-empty string`);
      return null;
    }

    const logoBlock = logoUrl
      ? `      <Img src="${logoUrl}" alt="${appName} logo" width="120" height="40" style={styles.logo} />`
      : `      <Text style={styles.logoText}>${appName}</Text>`;

    return `// emails/welcome.tsx
// Generated by react-email-templates. Requires: react-email, @react-email/components
// Install: npm install react-email @react-email/components

import {
  Body,
  Button,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Img,
  Link,
  Preview,
  Section,
  Text,
} from "@react-email/components";

interface WelcomeEmailProps {
  userName?: string;
  userEmail?: string;
  confirmUrl?: string;
}

export default function WelcomeEmail({
  userName = "there",
  userEmail = "",
  confirmUrl = "${appUrl}/confirm",
}: WelcomeEmailProps) {
  return (
    <Html lang="en" dir="ltr">
      <Head />
      <Preview>Welcome to ${appName} — let's get you started</Preview>
      <Body style={styles.body}>
        <Container style={styles.container}>
          <Section style={styles.header}>
${logoBlock}
          </Section>

          <Section style={styles.content}>
            <Heading style={styles.h1}>Welcome to ${appName}!</Heading>
            <Text style={styles.text}>
              Hi {userName},
            </Text>
            <Text style={styles.text}>
              Your account has been created{userEmail ? \` for \${userEmail}\` : ""}. We're thrilled
              to have you on board. Confirm your email address to activate your account and
              unlock all features.
            </Text>
            <Section style={styles.buttonContainer}>
              <Button href={confirmUrl} style={styles.button}>
                Confirm your email
              </Button>
            </Section>
            <Text style={styles.mutedText}>
              If the button doesn't work, copy and paste this link into your browser:
            </Text>
            <Link href={confirmUrl} style={styles.link}>
              {confirmUrl}
            </Link>
          </Section>

          <Hr style={styles.hr} />

          <Section style={styles.footer}>
            <Text style={styles.footerText}>
              If you didn't create an account, you can safely ignore this email.
            </Text>
            <Text style={styles.footerText}>
              Need help?{" "}
              <Link href="mailto:${supportEmail}" style={styles.footerLink}>
                Contact support
              </Link>
            </Text>
            <Text style={styles.footerText}>© {new Date().getFullYear()} ${appName}</Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}

WelcomeEmail.PreviewProps = {
  userName: "Alex",
  userEmail: "alex@example.com",
  confirmUrl: "${appUrl}/confirm?token=preview",
} satisfies WelcomeEmailProps;

const styles = {
  body: {
    backgroundColor: "#f6f9fc",
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  container: {
    backgroundColor: "#ffffff",
    margin: "0 auto",
    padding: "20px 0 48px",
    maxWidth: "580px",
    borderRadius: "8px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
  },
  header: {
    padding: "32px 40px 24px",
    borderBottom: "1px solid #e6ebf1",
  },
  logo: { display: "block" },
  logoText: {
    fontSize: "24px",
    fontWeight: "700",
    color: "${primaryColor}",
    margin: "0",
  },
  content: { padding: "32px 40px" },
  h1: {
    color: "#1a1a2e",
    fontSize: "28px",
    fontWeight: "700",
    lineHeight: "1.3",
    margin: "0 0 16px",
  },
  text: {
    color: "#4a5568",
    fontSize: "16px",
    lineHeight: "1.6",
    margin: "0 0 16px",
  },
  mutedText: {
    color: "#718096",
    fontSize: "14px",
    lineHeight: "1.5",
    margin: "16px 0 8px",
  },
  buttonContainer: { margin: "28px 0" },
  button: {
    backgroundColor: "${primaryColor}",
    borderRadius: "6px",
    color: "#ffffff",
    fontSize: "16px",
    fontWeight: "600",
    textDecoration: "none",
    textAlign: "center" as const,
    display: "inline-block",
    padding: "14px 32px",
  },
  link: {
    color: "${primaryColor}",
    fontSize: "14px",
    wordBreak: "break-all" as const,
  },
  hr: { borderColor: "#e6ebf1", margin: "0" },
  footer: { padding: "24px 40px 0" },
  footerText: {
    color: "#9ca3af",
    fontSize: "13px",
    lineHeight: "1.5",
    margin: "0 0 8px",
  },
  footerLink: { color: "#9ca3af", textDecoration: "underline" },
};
`;
  } catch (err) {
    console.error(`${PKG} generateWelcomeEmail: unexpected error: ${err.message}`);
    return null;
  }
}

// ─── Password Reset Email ──────────────────────────────────────────────────────

/**
 * Generate a password reset email React Email component as a file string.
 *
 * Write to `emails/password-reset.tsx`. The component expects a `resetUrl`
 * prop containing the signed reset link and a short `expiresIn` description.
 *
 * @param {object} [options]
 * @param {string} [options.appName="MyApp"]
 * @param {string} [options.appUrl="https://example.com"]
 * @param {string} [options.supportEmail="support@example.com"]
 * @param {string} [options.primaryColor="#6366f1"]
 * @param {number} [options.expiryMinutes=60]          - Token lifetime in minutes (shown in copy)
 * @returns {string|null}
 */
export function generatePasswordResetEmail(options = {}) {
  try {
    const {
      appName = "MyApp",
      appUrl = "https://example.com",
      supportEmail = "support@example.com",
      primaryColor = "#6366f1",
      expiryMinutes = 60,
    } = options;

    return `// emails/password-reset.tsx
// Generated by react-email-templates. Requires: react-email, @react-email/components

import {
  Body,
  Button,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Link,
  Preview,
  Section,
  Text,
} from "@react-email/components";

interface PasswordResetEmailProps {
  userName?: string;
  resetUrl?: string;
}

export default function PasswordResetEmail({
  userName = "there",
  resetUrl = "${appUrl}/reset-password?token=preview",
}: PasswordResetEmailProps) {
  return (
    <Html lang="en" dir="ltr">
      <Head />
      <Preview>Reset your ${appName} password</Preview>
      <Body style={styles.body}>
        <Container style={styles.container}>
          <Section style={styles.content}>
            <Heading style={styles.h1}>Reset your password</Heading>
            <Text style={styles.text}>Hi {userName},</Text>
            <Text style={styles.text}>
              We received a request to reset the password for your ${appName} account.
              Click the button below to choose a new password. This link expires in{" "}
              <strong>${expiryMinutes} minutes</strong>.
            </Text>
            <Section style={styles.buttonContainer}>
              <Button href={resetUrl} style={styles.button}>
                Reset password
              </Button>
            </Section>
            <Text style={styles.mutedText}>
              Or copy and paste this URL into your browser:
            </Text>
            <Link href={resetUrl} style={styles.link}>
              {resetUrl}
            </Link>

            <Hr style={styles.hr} />

            <Text style={styles.securityNote}>
              <strong>Didn't request this?</strong> Your account is safe. You can ignore
              this email — the link will expire automatically. If you're concerned, contact{" "}
              <Link href="mailto:${supportEmail}" style={styles.link}>
                ${supportEmail}
              </Link>
              .
            </Text>
          </Section>

          <Section style={styles.footer}>
            <Text style={styles.footerText}>© {new Date().getFullYear()} ${appName}</Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}

PasswordResetEmail.PreviewProps = {
  userName: "Alex",
  resetUrl: "${appUrl}/reset-password?token=preview",
} satisfies PasswordResetEmailProps;

const styles = {
  body: {
    backgroundColor: "#f6f9fc",
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  container: {
    backgroundColor: "#ffffff",
    margin: "0 auto",
    padding: "20px 0 48px",
    maxWidth: "580px",
    borderRadius: "8px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
  },
  content: { padding: "40px 40px 24px" },
  h1: {
    color: "#1a1a2e",
    fontSize: "26px",
    fontWeight: "700",
    lineHeight: "1.3",
    margin: "0 0 20px",
  },
  text: {
    color: "#4a5568",
    fontSize: "16px",
    lineHeight: "1.6",
    margin: "0 0 16px",
  },
  mutedText: {
    color: "#718096",
    fontSize: "14px",
    lineHeight: "1.5",
    margin: "20px 0 8px",
  },
  buttonContainer: { margin: "28px 0" },
  button: {
    backgroundColor: "${primaryColor}",
    borderRadius: "6px",
    color: "#ffffff",
    fontSize: "16px",
    fontWeight: "600",
    textDecoration: "none",
    textAlign: "center" as const,
    display: "inline-block",
    padding: "14px 32px",
  },
  link: { color: "${primaryColor}", wordBreak: "break-all" as const },
  hr: { borderColor: "#e6ebf1", margin: "24px 0" },
  securityNote: {
    color: "#718096",
    fontSize: "14px",
    lineHeight: "1.6",
    margin: "0",
    backgroundColor: "#f8fafc",
    borderRadius: "6px",
    padding: "16px",
  },
  footer: { padding: "0 40px" },
  footerText: {
    color: "#9ca3af",
    fontSize: "13px",
    margin: "0",
  },
};
`;
  } catch (err) {
    console.error(`${PKG} generatePasswordResetEmail: unexpected error: ${err.message}`);
    return null;
  }
}

// ─── Payment Receipt Email ─────────────────────────────────────────────────────

/**
 * Generate a payment receipt email React Email component as a file string.
 *
 * Write to `emails/payment-receipt.tsx`. The component accepts order line items
 * and renders a clean itemized receipt with subtotal, tax, and total rows.
 *
 * @param {object} [options]
 * @param {string} [options.appName="MyApp"]
 * @param {string} [options.appUrl="https://example.com"]
 * @param {string} [options.supportEmail="support@example.com"]
 * @param {string} [options.primaryColor="#6366f1"]
 * @param {string} [options.currency="USD"]               - ISO 4217 currency code for display hint
 * @returns {string|null}
 */
export function generatePaymentReceiptEmail(options = {}) {
  try {
    const {
      appName = "MyApp",
      appUrl = "https://example.com",
      supportEmail = "support@example.com",
      primaryColor = "#6366f1",
      currency = "USD",
    } = options;

    return `// emails/payment-receipt.tsx
// Generated by react-email-templates. Requires: react-email, @react-email/components

import {
  Body,
  Column,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Link,
  Preview,
  Row,
  Section,
  Text,
} from "@react-email/components";

interface LineItem {
  description: string;
  quantity: number;
  unitPrice: number; // in cents
}

interface PaymentReceiptEmailProps {
  customerName?: string;
  receiptNumber?: string;
  receiptDate?: string;
  items?: LineItem[];
  taxCents?: number;
  currency?: string;
  billingAddress?: string;
  last4?: string;
  receiptUrl?: string;
}

function formatCents(cents: number, currency = "${currency}"): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency,
    minimumFractionDigits: 2,
  }).format(cents / 100);
}

export default function PaymentReceiptEmail({
  customerName = "Valued Customer",
  receiptNumber = "REC-0001",
  receiptDate = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }),
  items = [{ description: "Pro Plan — Monthly", quantity: 1, unitPrice: 2900 }],
  taxCents = 0,
  currency = "${currency}",
  billingAddress = "",
  last4 = "",
  receiptUrl = "${appUrl}/receipts/preview",
}: PaymentReceiptEmailProps) {
  const subtotalCents = items.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0);
  const totalCents = subtotalCents + taxCents;

  return (
    <Html lang="en" dir="ltr">
      <Head />
      <Preview>Your ${appName} receipt — {receiptNumber}</Preview>
      <Body style={styles.body}>
        <Container style={styles.container}>
          <Section style={styles.header}>
            <Text style={styles.logoText}>${appName}</Text>
            <Text style={styles.receiptLabel}>Payment Receipt</Text>
          </Section>

          <Section style={styles.content}>
            <Heading style={styles.h1}>Thanks for your payment!</Heading>
            <Text style={styles.text}>
              Hi {customerName}, here's your receipt for the payment we received.
            </Text>

            <Section style={styles.metaBox}>
              <Row>
                <Column style={styles.metaCol}>
                  <Text style={styles.metaLabel}>Receipt number</Text>
                  <Text style={styles.metaValue}>{receiptNumber}</Text>
                </Column>
                <Column style={styles.metaCol}>
                  <Text style={styles.metaLabel}>Date</Text>
                  <Text style={styles.metaValue}>{receiptDate}</Text>
                </Column>
                {last4 && (
                  <Column style={styles.metaCol}>
                    <Text style={styles.metaLabel}>Payment method</Text>
                    <Text style={styles.metaValue}>•••• {last4}</Text>
                  </Column>
                )}
              </Row>
            </Section>

            <Section style={styles.tableContainer}>
              <Row style={styles.tableHeader}>
                <Column style={styles.colDesc}>
                  <Text style={styles.tableHeaderText}>Description</Text>
                </Column>
                <Column style={styles.colQty}>
                  <Text style={styles.tableHeaderTextRight}>Qty</Text>
                </Column>
                <Column style={styles.colAmount}>
                  <Text style={styles.tableHeaderTextRight}>Amount</Text>
                </Column>
              </Row>
              {items.map((item, i) => (
                <Row key={i} style={i % 2 === 1 ? styles.rowAlt : styles.row}>
                  <Column style={styles.colDesc}>
                    <Text style={styles.cellText}>{item.description}</Text>
                  </Column>
                  <Column style={styles.colQty}>
                    <Text style={styles.cellTextRight}>{item.quantity}</Text>
                  </Column>
                  <Column style={styles.colAmount}>
                    <Text style={styles.cellTextRight}>
                      {formatCents(item.quantity * item.unitPrice, currency)}
                    </Text>
                  </Column>
                </Row>
              ))}
            </Section>

            <Section style={styles.totalsContainer}>
              {taxCents > 0 && (
                <Row>
                  <Column>
                    <Text style={styles.totalLabel}>Subtotal</Text>
                  </Column>
                  <Column>
                    <Text style={styles.totalValue}>{formatCents(subtotalCents, currency)}</Text>
                  </Column>
                </Row>
              )}
              {taxCents > 0 && (
                <Row>
                  <Column>
                    <Text style={styles.totalLabel}>Tax</Text>
                  </Column>
                  <Column>
                    <Text style={styles.totalValue}>{formatCents(taxCents, currency)}</Text>
                  </Column>
                </Row>
              )}
              <Hr style={styles.totalDivider} />
              <Row>
                <Column>
                  <Text style={styles.grandTotalLabel}>Total</Text>
                </Column>
                <Column>
                  <Text style={styles.grandTotalValue}>{formatCents(totalCents, currency)}</Text>
                </Column>
              </Row>
            </Section>

            {billingAddress && (
              <Section style={styles.addressBlock}>
                <Text style={styles.metaLabel}>Billed to</Text>
                <Text style={styles.addressText}>{billingAddress}</Text>
              </Section>
            )}

            <Text style={styles.mutedText}>
              <Link href={receiptUrl} style={styles.link}>
                View or download this receipt
              </Link>
            </Text>
          </Section>

          <Hr style={styles.hr} />

          <Section style={styles.footer}>
            <Text style={styles.footerText}>
              Questions?{" "}
              <Link href="mailto:${supportEmail}" style={styles.footerLink}>
                ${supportEmail}
              </Link>
            </Text>
            <Text style={styles.footerText}>© {new Date().getFullYear()} ${appName}</Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}

PaymentReceiptEmail.PreviewProps = {
  customerName: "Alex Johnson",
  receiptNumber: "REC-2024-0042",
  receiptDate: "April 8, 2026",
  items: [
    { description: "Pro Plan — Monthly", quantity: 1, unitPrice: 2900 },
    { description: "Extra seats (3)", quantity: 3, unitPrice: 500 },
  ],
  taxCents: 435,
  currency: "${currency}",
  last4: "4242",
  receiptUrl: "${appUrl}/receipts/preview",
} satisfies PaymentReceiptEmailProps;

const styles = {
  body: {
    backgroundColor: "#f6f9fc",
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  container: {
    backgroundColor: "#ffffff",
    margin: "0 auto",
    padding: "0 0 48px",
    maxWidth: "600px",
    borderRadius: "8px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
  },
  header: {
    backgroundColor: "${primaryColor}",
    padding: "28px 40px",
    borderRadius: "8px 8px 0 0",
  },
  logoText: {
    color: "#ffffff",
    fontSize: "22px",
    fontWeight: "700",
    margin: "0 0 4px",
  },
  receiptLabel: {
    color: "rgba(255,255,255,0.8)",
    fontSize: "13px",
    margin: "0",
  },
  content: { padding: "32px 40px 0" },
  h1: {
    color: "#1a1a2e",
    fontSize: "24px",
    fontWeight: "700",
    margin: "0 0 12px",
  },
  text: {
    color: "#4a5568",
    fontSize: "16px",
    lineHeight: "1.6",
    margin: "0 0 24px",
  },
  metaBox: {
    backgroundColor: "#f8fafc",
    borderRadius: "6px",
    padding: "16px",
    margin: "0 0 24px",
  },
  metaCol: { paddingRight: "24px" },
  metaLabel: { color: "#9ca3af", fontSize: "12px", margin: "0 0 2px", textTransform: "uppercase" as const, letterSpacing: "0.05em" },
  metaValue: { color: "#1a1a2e", fontSize: "14px", fontWeight: "600", margin: "0" },
  tableContainer: { margin: "0 0 4px" },
  tableHeader: { backgroundColor: "#f1f5f9" },
  tableHeaderText: { color: "#64748b", fontSize: "12px", fontWeight: "600", textTransform: "uppercase" as const, letterSpacing: "0.05em", padding: "10px 8px", margin: "0" },
  tableHeaderTextRight: { color: "#64748b", fontSize: "12px", fontWeight: "600", textTransform: "uppercase" as const, letterSpacing: "0.05em", padding: "10px 8px", margin: "0", textAlign: "right" as const },
  row: { borderBottom: "1px solid #f1f5f9" },
  rowAlt: { backgroundColor: "#fafafa", borderBottom: "1px solid #f1f5f9" },
  colDesc: { width: "60%", padding: "12px 8px" },
  colQty: { width: "15%", padding: "12px 8px", textAlign: "center" as const },
  colAmount: { width: "25%", padding: "12px 8px", textAlign: "right" as const },
  cellText: { color: "#374151", fontSize: "14px", margin: "0" },
  cellTextRight: { color: "#374151", fontSize: "14px", margin: "0", textAlign: "right" as const },
  totalsContainer: { margin: "8px 0 24px", padding: "0 8px" },
  totalLabel: { color: "#6b7280", fontSize: "14px", margin: "4px 0" },
  totalValue: { color: "#374151", fontSize: "14px", margin: "4px 0", textAlign: "right" as const },
  totalDivider: { borderColor: "#e5e7eb", margin: "8px 0" },
  grandTotalLabel: { color: "#1a1a2e", fontSize: "16px", fontWeight: "700", margin: "8px 0 0" },
  grandTotalValue: { color: "#1a1a2e", fontSize: "16px", fontWeight: "700", margin: "8px 0 0", textAlign: "right" as const },
  addressBlock: { margin: "0 0 20px" },
  addressText: { color: "#4a5568", fontSize: "14px", margin: "4px 0 0", whiteSpace: "pre-line" as const },
  mutedText: { color: "#718096", fontSize: "14px", margin: "0 0 0" },
  link: { color: "${primaryColor}" },
  hr: { borderColor: "#e6ebf1", margin: "32px 0 0" },
  footer: { padding: "20px 40px 0" },
  footerText: { color: "#9ca3af", fontSize: "13px", margin: "0 0 4px" },
  footerLink: { color: "#9ca3af", textDecoration: "underline" },
};
`;
  } catch (err) {
    console.error(`${PKG} generatePaymentReceiptEmail: unexpected error: ${err.message}`);
    return null;
  }
}

// ─── Team Invitation Email ─────────────────────────────────────────────────────

/**
 * Generate a team invitation email React Email component as a file string.
 *
 * Write to `emails/team-invitation.tsx`. The component expects the inviter's
 * name, the team name, and a signed `inviteUrl`.
 *
 * @param {object} [options]
 * @param {string} [options.appName="MyApp"]
 * @param {string} [options.appUrl="https://example.com"]
 * @param {string} [options.supportEmail="support@example.com"]
 * @param {string} [options.primaryColor="#6366f1"]
 * @param {number} [options.expiryDays=7]               - Invite link validity in days
 * @returns {string|null}
 */
export function generateTeamInvitationEmail(options = {}) {
  try {
    const {
      appName = "MyApp",
      appUrl = "https://example.com",
      supportEmail = "support@example.com",
      primaryColor = "#6366f1",
      expiryDays = 7,
    } = options;

    return `// emails/team-invitation.tsx
// Generated by react-email-templates. Requires: react-email, @react-email/components

import {
  Body,
  Button,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Img,
  Link,
  Preview,
  Section,
  Text,
} from "@react-email/components";

interface TeamInvitationEmailProps {
  inviteeName?: string;
  inviterName?: string;
  inviterEmail?: string;
  inviterAvatarUrl?: string;
  teamName?: string;
  teamRole?: string;
  inviteUrl?: string;
}

export default function TeamInvitationEmail({
  inviteeName = "",
  inviterName = "A teammate",
  inviterEmail = "",
  inviterAvatarUrl = "",
  teamName = "the team",
  teamRole = "Member",
  inviteUrl = "${appUrl}/invite?token=preview",
}: TeamInvitationEmailProps) {
  const greeting = inviteeName ? \`Hi \${inviteeName},\` : "Hi there,";

  return (
    <Html lang="en" dir="ltr">
      <Head />
      <Preview>
        {inviterName} invited you to join {teamName} on ${appName}
      </Preview>
      <Body style={styles.body}>
        <Container style={styles.container}>
          <Section style={styles.content}>
            {inviterAvatarUrl && (
              <Img
                src={inviterAvatarUrl}
                alt={inviterName}
                width="48"
                height="48"
                style={styles.avatar}
              />
            )}
            <Heading style={styles.h1}>
              You've been invited to join <em>{teamName}</em>
            </Heading>
            <Text style={styles.text}>{greeting}</Text>
            <Text style={styles.text}>
              <strong>{inviterName}</strong>
              {inviterEmail ? \` (\${inviterEmail})\` : ""} has invited you to join{" "}
              <strong>{teamName}</strong> on ${appName} as a{" "}
              <strong>{teamRole}</strong>.
            </Text>

            <Section style={styles.inviteCard}>
              <Text style={styles.inviteCardText}>
                🏢 <strong>{teamName}</strong> · {teamRole}
              </Text>
            </Section>

            <Section style={styles.buttonContainer}>
              <Button href={inviteUrl} style={styles.button}>
                Accept invitation
              </Button>
            </Section>

            <Text style={styles.mutedText}>
              This invitation expires in <strong>${expiryDays} days</strong>. If you don't
              have an account yet, you'll be prompted to create one after accepting.
            </Text>
            <Text style={styles.mutedText}>
              Or copy this link:{" "}
              <Link href={inviteUrl} style={styles.link}>
                {inviteUrl}
              </Link>
            </Text>
          </Section>

          <Hr style={styles.hr} />

          <Section style={styles.footer}>
            <Text style={styles.footerText}>
              If you weren't expecting this invitation, you can ignore it. If you have
              concerns, contact{" "}
              <Link href="mailto:${supportEmail}" style={styles.footerLink}>
                ${supportEmail}
              </Link>
              .
            </Text>
            <Text style={styles.footerText}>© {new Date().getFullYear()} ${appName}</Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}

TeamInvitationEmail.PreviewProps = {
  inviteeName: "Jordan",
  inviterName: "Sam Rivera",
  inviterEmail: "sam@acme.com",
  teamName: "Acme Engineering",
  teamRole: "Developer",
  inviteUrl: "${appUrl}/invite?token=preview",
} satisfies TeamInvitationEmailProps;

const styles = {
  body: {
    backgroundColor: "#f6f9fc",
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  container: {
    backgroundColor: "#ffffff",
    margin: "0 auto",
    padding: "0 0 48px",
    maxWidth: "560px",
    borderRadius: "8px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
  },
  content: { padding: "40px 40px 24px" },
  avatar: {
    borderRadius: "50%",
    display: "block",
    marginBottom: "20px",
  },
  h1: {
    color: "#1a1a2e",
    fontSize: "24px",
    fontWeight: "700",
    lineHeight: "1.35",
    margin: "0 0 20px",
  },
  text: {
    color: "#4a5568",
    fontSize: "16px",
    lineHeight: "1.6",
    margin: "0 0 16px",
  },
  inviteCard: {
    backgroundColor: "#f0f4ff",
    border: "1px solid #c7d2fe",
    borderRadius: "8px",
    padding: "16px 20px",
    margin: "20px 0",
  },
  inviteCardText: {
    color: "#3730a3",
    fontSize: "15px",
    fontWeight: "500",
    margin: "0",
  },
  buttonContainer: { margin: "28px 0 20px" },
  button: {
    backgroundColor: "${primaryColor}",
    borderRadius: "6px",
    color: "#ffffff",
    fontSize: "16px",
    fontWeight: "600",
    textDecoration: "none",
    textAlign: "center" as const,
    display: "inline-block",
    padding: "14px 32px",
  },
  mutedText: {
    color: "#718096",
    fontSize: "14px",
    lineHeight: "1.6",
    margin: "0 0 12px",
  },
  link: { color: "${primaryColor}", wordBreak: "break-all" as const },
  hr: { borderColor: "#e6ebf1", margin: "0" },
  footer: { padding: "24px 40px 0" },
  footerText: {
    color: "#9ca3af",
    fontSize: "13px",
    lineHeight: "1.5",
    margin: "0 0 8px",
  },
  footerLink: { color: "#9ca3af", textDecoration: "underline" },
};
`;
  } catch (err) {
    console.error(`${PKG} generateTeamInvitationEmail: unexpected error: ${err.message}`);
    return null;
  }
}

// ─── Notification Digest Email ─────────────────────────────────────────────────

/**
 * Generate a notification digest email React Email component as a file string.
 *
 * Write to `emails/notification-digest.tsx`. The component renders a list of
 * grouped notifications (e.g. weekly activity summary) with icon-style badges,
 * labels, and individual deep-link URLs.
 *
 * @param {object} [options]
 * @param {string} [options.appName="MyApp"]
 * @param {string} [options.appUrl="https://example.com"]
 * @param {string} [options.supportEmail="support@example.com"]
 * @param {string} [options.primaryColor="#6366f1"]
 * @param {string} [options.digestPeriod="weekly"]     - Label shown in subject/heading ("daily" | "weekly" | "monthly")
 * @returns {string|null}
 */
export function generateNotificationDigestEmail(options = {}) {
  try {
    const {
      appName = "MyApp",
      appUrl = "https://example.com",
      supportEmail = "support@example.com",
      primaryColor = "#6366f1",
      digestPeriod = "weekly",
    } = options;

    const periodLabel = digestPeriod.charAt(0).toUpperCase() + digestPeriod.slice(1);

    return `// emails/notification-digest.tsx
// Generated by react-email-templates. Requires: react-email, @react-email/components

import {
  Body,
  Button,
  Column,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Link,
  Preview,
  Row,
  Section,
  Text,
} from "@react-email/components";

interface Notification {
  /** Short category label, e.g. "Comment", "Mention", "New follower" */
  type: string;
  /** Icon/emoji to display beside the type */
  icon: string;
  /** One-line summary of the notification */
  title: string;
  /** Optional secondary line of context */
  description?: string;
  /** ISO timestamp string */
  timestamp: string;
  /** Deep-link to the relevant item in the app */
  actionUrl: string;
  /** Label for the action link */
  actionLabel?: string;
}

interface NotificationDigestEmailProps {
  userName?: string;
  notifications?: Notification[];
  digestPeriodLabel?: string;
  dashboardUrl?: string;
  unsubscribeUrl?: string;
}

function formatTimestamp(iso: string): string {
  try {
    return new Date(iso).toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  } catch {
    return iso;
  }
}

export default function NotificationDigestEmail({
  userName = "there",
  notifications = [],
  digestPeriodLabel = "${periodLabel}",
  dashboardUrl = "${appUrl}/dashboard",
  unsubscribeUrl = "${appUrl}/settings/notifications",
}: NotificationDigestEmailProps) {
  const count = notifications.length;

  return (
    <Html lang="en" dir="ltr">
      <Head />
      <Preview>
        Your {digestPeriodLabel.toLowerCase()} digest — {count} update{count !== 1 ? "s" : ""} from ${appName}
      </Preview>
      <Body style={styles.body}>
        <Container style={styles.container}>
          <Section style={styles.header}>
            <Text style={styles.logoText}>${appName}</Text>
            <Text style={styles.digestLabel}>{digestPeriodLabel} Digest</Text>
          </Section>

          <Section style={styles.content}>
            <Heading style={styles.h1}>
              {count} update{count !== 1 ? "s" : ""} for you, {userName}
            </Heading>
            <Text style={styles.text}>
              Here's a summary of activity from the past{" "}
              {digestPeriodLabel.toLowerCase() === "daily"
                ? "24 hours"
                : digestPeriodLabel.toLowerCase() === "weekly"
                ? "7 days"
                : "30 days"}
              .
            </Text>

            {count === 0 ? (
              <Section style={styles.emptyState}>
                <Text style={styles.emptyText}>
                  No new notifications this period. Check back next time!
                </Text>
              </Section>
            ) : (
              <Section style={styles.notificationList}>
                {notifications.map((n, i) => (
                  <Section
                    key={i}
                    style={i < notifications.length - 1 ? styles.notifRow : styles.notifRowLast}
                  >
                    <Row>
                      <Column style={styles.iconCol}>
                        <Text style={styles.icon}>{n.icon}</Text>
                      </Column>
                      <Column style={styles.bodyCol}>
                        <Text style={styles.notifType}>{n.type}</Text>
                        <Text style={styles.notifTitle}>{n.title}</Text>
                        {n.description && (
                          <Text style={styles.notifDesc}>{n.description}</Text>
                        )}
                        <Row>
                          <Column>
                            <Text style={styles.notifTime}>{formatTimestamp(n.timestamp)}</Text>
                          </Column>
                          <Column style={styles.actionCol}>
                            <Link href={n.actionUrl} style={styles.actionLink}>
                              {n.actionLabel ?? "View →"}
                            </Link>
                          </Column>
                        </Row>
                      </Column>
                    </Row>
                  </Section>
                ))}
              </Section>
            )}

            <Section style={styles.cta}>
              <Button href={dashboardUrl} style={styles.button}>
                Go to dashboard
              </Button>
            </Section>
          </Section>

          <Hr style={styles.hr} />

          <Section style={styles.footer}>
            <Text style={styles.footerText}>
              You're receiving this because you have ${periodLabel.toLowerCase()} digests enabled.{" "}
              <Link href={unsubscribeUrl} style={styles.footerLink}>
                Manage preferences
              </Link>
            </Text>
            <Text style={styles.footerText}>
              Questions?{" "}
              <Link href="mailto:${supportEmail}" style={styles.footerLink}>
                ${supportEmail}
              </Link>
            </Text>
            <Text style={styles.footerText}>© {new Date().getFullYear()} ${appName}</Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}

NotificationDigestEmail.PreviewProps = {
  userName: "Alex",
  digestPeriodLabel: "${periodLabel}",
  dashboardUrl: "${appUrl}/dashboard",
  unsubscribeUrl: "${appUrl}/settings/notifications",
  notifications: [
    {
      type: "Comment",
      icon: "💬",
      title: "Sam left a comment on your post",
      description: '"Great write-up! One small note on the caching section..."',
      timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      actionUrl: "${appUrl}/posts/1#comment-42",
      actionLabel: "View comment →",
    },
    {
      type: "Mention",
      icon: "@",
      title: "You were mentioned in #engineering",
      description: "@alex can you review the PR before EOD?",
      timestamp: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
      actionUrl: "${appUrl}/channels/engineering",
      actionLabel: "Go to channel →",
    },
    {
      type: "New follower",
      icon: "👤",
      title: "Jordan started following you",
      timestamp: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
      actionUrl: "${appUrl}/users/jordan",
      actionLabel: "View profile →",
    },
  ],
} satisfies NotificationDigestEmailProps;

const styles = {
  body: {
    backgroundColor: "#f6f9fc",
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  container: {
    backgroundColor: "#ffffff",
    margin: "0 auto",
    padding: "0 0 48px",
    maxWidth: "600px",
    borderRadius: "8px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
  },
  header: {
    backgroundColor: "${primaryColor}",
    padding: "24px 40px",
    borderRadius: "8px 8px 0 0",
  },
  logoText: { color: "#ffffff", fontSize: "20px", fontWeight: "700", margin: "0 0 2px" },
  digestLabel: { color: "rgba(255,255,255,0.75)", fontSize: "13px", margin: "0" },
  content: { padding: "32px 40px 0" },
  h1: { color: "#1a1a2e", fontSize: "22px", fontWeight: "700", margin: "0 0 12px" },
  text: { color: "#4a5568", fontSize: "16px", lineHeight: "1.6", margin: "0 0 24px" },
  emptyState: {
    backgroundColor: "#f8fafc",
    borderRadius: "8px",
    padding: "32px",
    textAlign: "center" as const,
    margin: "0 0 24px",
  },
  emptyText: { color: "#9ca3af", fontSize: "15px", margin: "0" },
  notificationList: {
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
    overflow: "hidden",
    margin: "0 0 24px",
  },
  notifRow: { borderBottom: "1px solid #e5e7eb", padding: "16px" },
  notifRowLast: { padding: "16px" },
  iconCol: { width: "44px", verticalAlign: "top" as const },
  icon: {
    fontSize: "20px",
    margin: "2px 0 0",
    width: "32px",
    height: "32px",
    lineHeight: "32px",
    textAlign: "center" as const,
    backgroundColor: "#f1f5f9",
    borderRadius: "6px",
    display: "block",
  },
  bodyCol: { verticalAlign: "top" as const },
  notifType: {
    color: "#6b7280",
    fontSize: "11px",
    fontWeight: "600",
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
    margin: "0 0 3px",
  },
  notifTitle: { color: "#1a1a2e", fontSize: "14px", fontWeight: "500", margin: "0 0 4px" },
  notifDesc: { color: "#6b7280", fontSize: "13px", lineHeight: "1.5", margin: "0 0 8px" },
  notifTime: { color: "#9ca3af", fontSize: "12px", margin: "0" },
  actionCol: { textAlign: "right" as const },
  actionLink: { color: "${primaryColor}", fontSize: "13px", fontWeight: "500" },
  cta: { margin: "8px 0 32px" },
  button: {
    backgroundColor: "${primaryColor}",
    borderRadius: "6px",
    color: "#ffffff",
    fontSize: "15px",
    fontWeight: "600",
    textDecoration: "none",
    textAlign: "center" as const,
    display: "inline-block",
    padding: "12px 28px",
  },
  hr: { borderColor: "#e6ebf1", margin: "0" },
  footer: { padding: "24px 40px 0" },
  footerText: { color: "#9ca3af", fontSize: "13px", lineHeight: "1.5", margin: "0 0 6px" },
  footerLink: { color: "#9ca3af", textDecoration: "underline" },
};
`;
  } catch (err) {
    console.error(`${PKG} generateNotificationDigestEmail: unexpected error: ${err.message}`);
    return null;
  }
}

// ─── Inline CSS Helper ─────────────────────────────────────────────────────────

/**
 * Generate an inline CSS helper module as a file string.
 *
 * Write to `emails/utils/inlineCss.ts`. Exports `px`, `pct`, `rgb`, and
 * `mergeStyles` — small utilities that make React Email style objects more
 * ergonomic when building custom templates or extending generated ones.
 *
 * @returns {string} Complete TS source string for the helper module
 */
export function generateInlineCssHelper() {
  try {
    return `// emails/utils/inlineCss.ts
// Generated by react-email-templates.
// Utilities for working with React Email inline style objects.

import type { CSSProperties } from "react";

/**
 * Convert a pixel number to a CSS px string.
 * Useful when you want to keep numeric values in constants but pass strings to style props.
 *
 * @example px(16) // "16px"
 */
export function px(value: number): string {
  return \`\${value}px\`;
}

/**
 * Convert a 0-100 number to a CSS percentage string.
 *
 * @example pct(50) // "50%"
 */
export function pct(value: number): string {
  return \`\${value}%\`;
}

/**
 * Build an rgba CSS color string.
 *
 * @example rgba(99, 102, 241, 0.15) // "rgba(99,102,241,0.15)"
 */
export function rgba(r: number, g: number, b: number, a = 1): string {
  return \`rgba(\${r},\${g},\${b},\${a})\`;
}

/**
 * Merge two or more React Email style objects, with later objects overriding earlier ones.
 * Strips undefined values so React Email doesn't emit empty attributes.
 *
 * @example
 *   const style = mergeStyles(base.text, isError && base.errorText);
 */
export function mergeStyles(
  ...sources: Array<CSSProperties | false | null | undefined>
): CSSProperties {
  return Object.fromEntries(
    Object.entries(
      Object.assign({}, ...sources.filter(Boolean))
    ).filter(([, v]) => v !== undefined)
  ) as CSSProperties;
}

/**
 * Build a shorthand margin style object from 1-4 values (same as CSS margin shorthand).
 *
 * @example margin(16)           // { marginTop: 16, marginRight: 16, marginBottom: 16, marginLeft: 16 }
 * @example margin(8, 16)        // top/bottom=8, left/right=16
 * @example margin(8, 16, 24)    // top=8, left/right=16, bottom=24
 * @example margin(8, 16, 24, 0) // top=8, right=16, bottom=24, left=0
 */
export function margin(top: number, right?: number, bottom?: number, left?: number): CSSProperties {
  const r = right ?? top;
  const b = bottom ?? top;
  const l = left ?? r;
  return { marginTop: top, marginRight: r, marginBottom: b, marginLeft: l };
}

/**
 * Build a shorthand padding style object from 1-4 values.
 *
 * @example padding(24, 40) // { paddingTop: 24, paddingRight: 40, paddingBottom: 24, paddingLeft: 40 }
 */
export function padding(top: number, right?: number, bottom?: number, left?: number): CSSProperties {
  const r = right ?? top;
  const b = bottom ?? top;
  const l = left ?? r;
  return { paddingTop: top, paddingRight: r, paddingBottom: b, paddingLeft: l };
}

/**
 * Build a border shorthand style as individual properties.
 * React Email renders border longhand more reliably across email clients than the shorthand.
 *
 * @example border(1, "solid", "#e5e7eb")
 */
export function border(
  widthPx: number,
  style: "solid" | "dashed" | "dotted" | "none",
  color: string
): CSSProperties {
  return {
    borderTopWidth: widthPx,
    borderRightWidth: widthPx,
    borderBottomWidth: widthPx,
    borderLeftWidth: widthPx,
    borderTopStyle: style,
    borderRightStyle: style,
    borderBottomStyle: style,
    borderLeftStyle: style,
    borderTopColor: color,
    borderRightColor: color,
    borderBottomColor: color,
    borderLeftColor: color,
  };
}
`;
  } catch (err) {
    console.error(`${PKG} generateInlineCssHelper: unexpected error: ${err.message}`);
    return null;
  }
}

// ─── Plain-Text Fallback Generator ────────────────────────────────────────────

/**
 * Generate plain-text fallback strings for each template type.
 *
 * Plain text is required by some ESPs and improves deliverability.
 * Pass the same props you'd use for the React component; receive a
 * formatted plain-text string suitable for the `text` field of your send call.
 *
 * @param {"welcome"|"password-reset"|"payment-receipt"|"team-invitation"|"notification-digest"} templateType
 * @param {object} props - Same props as the corresponding React Email component
 * @returns {string|null} Plain-text email body, or null on invalid template type
 */
export function generatePlainTextFallback(templateType, props = {}) {
  try {
    switch (templateType) {
      case "welcome": {
        const { appName = "MyApp", userName = "there", confirmUrl = "" } = props;
        return [
          `Welcome to ${appName}!`,
          "",
          `Hi ${userName},`,
          "",
          `Your account has been created. Please confirm your email address to activate your account.`,
          "",
          confirmUrl ? `Confirm here: ${confirmUrl}` : "",
          "",
          `If you didn't create an account, you can safely ignore this email.`,
        ]
          .filter((l) => l !== undefined)
          .join("\n");
      }

      case "password-reset": {
        const { appName = "MyApp", userName = "there", resetUrl = "", expiryMinutes = 60 } = props;
        return [
          `Reset your ${appName} password`,
          "",
          `Hi ${userName},`,
          "",
          `We received a request to reset your password. Click the link below to choose a new password.`,
          `This link expires in ${expiryMinutes} minutes.`,
          "",
          resetUrl ? `Reset password: ${resetUrl}` : "",
          "",
          `If you didn't request a password reset, you can safely ignore this email.`,
        ].join("\n");
      }

      case "payment-receipt": {
        const {
          appName = "MyApp",
          customerName = "Valued Customer",
          receiptNumber = "",
          receiptDate = "",
          items = [],
          taxCents = 0,
          currency = "USD",
          receiptUrl = "",
        } = props;

        const fmt = (cents) =>
          new Intl.NumberFormat("en-US", { style: "currency", currency }).format(cents / 100);

        const subtotal = items.reduce((s, i) => s + (i.quantity ?? 1) * (i.unitPrice ?? 0), 0);
        const total = subtotal + taxCents;

        const itemLines = items.map(
          (i) =>
            `  ${i.description} (x${i.quantity ?? 1}) — ${fmt((i.quantity ?? 1) * (i.unitPrice ?? 0))}`
        );

        return [
          `${appName} Payment Receipt`,
          receiptNumber ? `Receipt: ${receiptNumber}` : "",
          receiptDate ? `Date: ${receiptDate}` : "",
          "",
          `Hi ${customerName},`,
          "",
          `Thank you for your payment! Here is your receipt:`,
          "",
          "─────────────────────────────",
          ...itemLines,
          taxCents > 0 ? `  Tax — ${fmt(taxCents)}` : "",
          "─────────────────────────────",
          `  Total — ${fmt(total)}`,
          "",
          receiptUrl ? `View receipt: ${receiptUrl}` : "",
        ]
          .filter((l) => l !== undefined)
          .join("\n");
      }

      case "team-invitation": {
        const {
          appName = "MyApp",
          inviteeName = "",
          inviterName = "A teammate",
          teamName = "the team",
          teamRole = "Member",
          inviteUrl = "",
          expiryDays = 7,
        } = props;

        const greeting = inviteeName ? `Hi ${inviteeName},` : "Hi there,";

        return [
          `You've been invited to join ${teamName} on ${appName}`,
          "",
          greeting,
          "",
          `${inviterName} has invited you to join ${teamName} as a ${teamRole}.`,
          "",
          inviteUrl ? `Accept invitation: ${inviteUrl}` : "",
          "",
          `This invitation expires in ${expiryDays} days.`,
          "",
          `If you weren't expecting this invitation, you can ignore this email.`,
        ].join("\n");
      }

      case "notification-digest": {
        const {
          appName = "MyApp",
          userName = "there",
          notifications = [],
          digestPeriodLabel = "Weekly",
          dashboardUrl = "",
          unsubscribeUrl = "",
        } = props;

        const notifLines = notifications.flatMap((n) => [
          `[${n.type}] ${n.icon ? n.icon + " " : ""}${n.title}`,
          n.description ? `  ${n.description}` : "",
          n.actionUrl ? `  ${n.actionLabel ?? "View"}: ${n.actionUrl}` : "",
          "",
        ]);

        return [
          `${appName} — Your ${digestPeriodLabel} Digest`,
          "",
          `Hi ${userName},`,
          "",
          notifications.length === 0
            ? "No new notifications this period."
            : `You have ${notifications.length} update${notifications.length !== 1 ? "s" : ""}:`,
          "",
          ...notifLines,
          dashboardUrl ? `Go to dashboard: ${dashboardUrl}` : "",
          "",
          unsubscribeUrl ? `Manage notification preferences: ${unsubscribeUrl}` : "",
        ]
          .filter((l) => l !== undefined)
          .join("\n");
      }

      default:
        console.error(
          `${PKG} generatePlainTextFallback: unknown templateType "${templateType}". ` +
            `Valid types: welcome, password-reset, payment-receipt, team-invitation, notification-digest`
        );
        return null;
    }
  } catch (err) {
    console.error(`${PKG} generatePlainTextFallback: unexpected error: ${err.message}`);
    return null;
  }
}
